config/routes.rb
Rails.application.routes.draw do
 devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

 root to: 'customer/homes#top'

 namespace :admin do
  resources :genres, only:[:index, :new, :create, :update, :destroy]
  resources :notifications, only: [:index]
  resources :customers do
   patch 'withdrawal'
  end
 end

 namespace :customer do
   resources :genres, only:[:index, :create, :new] do
    resources :categories do
     resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
     end
    end
   end

   get 'reports/:post_id' => 'posts#report', as: 'report'

   resources :customers do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    patch 'withdrawal'
  end
  get 'about' => 'homes#about'
  resources :notifications, only: [:index]
  get 'search' => 'searches#search'
  get 'tag_search' => 'searches#tag_search'
end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :categories, dependent: :destroy
  validates :name,    length: { in: 1..15 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController


  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def index
    @genres = Genre.all
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params_update)
    redirect_to admin_genres_path
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :enable)
  end

  def genre_params_update
    params.require(:genre).permit(:enable)
  end
end

app/controllers/customer/genres_controller.rb
class Customer::GenresController < ApplicationController
  def index
   @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
      @genre = Genre.new(genre_params)
    if
      @genre.save
      flash[:notice] = "追加して欲しいジャンルを送信しました"
      redirect_to customer_genres_path
    else
      flash.now[:notice] = "追加して欲しいジャンルを入力してください"
      render :new
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/customer/genres_helper.rb
module Customer::GenresHelper
end

app/views/admin/genres/_genre.html.erb
<div class="text-success"><%= flash[:notice] %></div>
<div class="container">
  <div class="row">
   <h1 class="mt-5 h1">ジャンル一覧</h1>
  </div>
  <div class="row">
    <% genres.each do |genre| %>
        <% if admin_signed_in? %>
          <div class="col-md-6 text-center mt-5"><%= link_to genre.name, customer_genre_categories_path(genre), class: "btn genre-btn" %>
          <%= form_with model:genre, url: admin_genre_path(genre), method: :patch, local: true do |f| %>
          <%= f.radio_button :enable, :true %>
          <%= f.label :enable, "有効", {value: :true, style: "display: inline-block;"} %>
          <%= f.radio_button :enable, :false %>
          <%= f.label :enable, "無効", {value: :false, style: "display: inline-block;"} %>
          <%= f.submit "更新"%><br>
          <%= link_to "削除", admin_genre_path(genre), method: :delete, class: "btn btn-outline-danger" %>
          </div>
        <% end %>
        <% else %>
         <% if genre.enable == true %>
          <div class="col-md-6 text-center mt-5"><%= link_to genre.name, customer_genre_categories_path(genre), class: "btn genre-btn" %></div>
         <% end %>
        <% end %>
    <% end %>

  </div>
  </div>
</div>
<% if current_customer.present? %>
<div class="text-right">新しいジャンルを追加したい場合は<%= link_to "こちら", new_customer_genre_path %>からお問い合わせください！</div>
<%end%>

app/views/admin/genres/index.html.erb
<div class="col-lg-10 mt-5 text-right"><%= link_to "", new_admin_genre_path, class: "fas fa-plus fa-5x"%></div>
<%= render 'admin/genres/genre', genres: @genres %>

app/views/admin/genres/new.html.erb
<div class="container">
 <div class="row">
  <h1 class="h1 mt-5">ジャンル登録</h1>
 </div>



  <div class="mt-5">
   <%= form_with model: @genre, url: admin_genres_path, local:true do |f| %>
    <%= f.label "ジャンル名"%>
    <%= f.text_field :name %><br>
    <%= f.submit "ジャンル新規登録!", class: "btn btn-success ml-5 mt-2"%>
   <% end %>
  </div>
 </div>
</div>