config/routes.rb
Rails.application.routes.draw do
 devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

 root to: 'customer/homes#top'

 namespace :admin do
  resources :genres, only:[:index, :new, :create, :update, :destroy]
  resources :notifications, only: [:index]
  resources :customers do
   patch 'withdrawal'
  end
 end

 namespace :customer do
   resources :genres, only:[:index, :create, :new] do
    resources :categories do
     resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
     end
    end
   end

   get 'reports/:post_id' => 'posts#report', as: 'report'

   resources :customers do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    patch 'withdrawal'
  end
  get 'about' => 'homes#about'
  resources :notifications, only: [:index]
  get 'search' => 'searches#search'
  get 'tag_search' => 'searches#tag_search'
end

end

app/models/customer.rb
class Customer < ApplicationRecord

 validates :email, presence: true
 validates :last_name,    length: { in: 1..15 }
 validates :first_name,    length: { in: 1..15 }
 validates :last_name_kana,    length: { in: 1..15 }
 validates :first_name_kana,    length: { in: 1..15 }
 validates :nickname,    length: { in: 1..15 }
 validates :body,    length: { maximum: 75 }


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 default_scope -> { order(created_at: :desc) }

 attachment :image
 has_many :categories, dependent: :destroy
 has_many :posts, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :comments, dependent: :destroy
 def active_for_authentication?
   super && (self.is_deleted == false)
  # デフォルトがフォルスならtrueを返す
 end

 has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
# relationshipをreverse_of_relationshipsに置き換える記述。主キーはfollowed_id
 has_many :followers, through: :reverse_of_relationships, source: :follower
#  自分をフォローしている人

 has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
 has_many :followings, through: :relationships, source: :followed

 has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
 # 自分からの通知、通知を送った人
 has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
 # 相手からの通知、通知が送られた人

  acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests


 def follow(customer_id)
     relationships.create(followed_id: customer_id)
 end

 def unfollow(customer_id)
     relationships.find_by(followed_id: customer_id).destroy
 end

 def following?(customer)
     followings.include?(customer)
    #  include=対象の配列に因数が含まれていればtrueを返す。含まれていればフォローしている
 end

 def create_notification_follow(current_customer)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_customer.id, id, 'follow'])
    if temp.blank?
      notification = current_customer.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
 end
  # 同じ人が何回もフォローしても通知が来ないようにする

 def self.search(word)
  @customers = Customer.where("nickname LIKE ?","%#{word}%")
 end

 def current_user?(current_customer)
   id == current_customer.id
 end



end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def withdrawal
   @customer = Customer.find(params[:customer_id])
   @customer.update(is_deleted: true)
   redirect_to customer_customers_path
  end
end

app/controllers/customer/categories_controller.rb
class Customer::CategoriesController < ApplicationController
 before_action :authenticate_customer!,except: [:index]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.genre_id = params[:genre_id]
    @category.customer_id = current_customer.id
    if
     @category.save
     redirect_to customer_genre_categories_path
    else
      render :new
    end
  end

  def index
    @categories = Category.where(genre_id: params[:genre_id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    category.update(category_params)
    redirect_to customer_genre_categories_path(category.genre_id)

  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to customer_genre_categories_path(category.genre_id)
  end

  private
  def category_params
    params.require(:category).permit(:name,:image)
  end


end

app/controllers/customer/comments_controller.rb
class Customer::CommentsController < ApplicationController
   before_action :authenticate_customer!
  def create
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:post_id])
    comment = current_customer.comments.new(comment_params)
    comment.post_id = @post.id
    if
      comment.save
      # 通知
      post = comment.post
      post.create_notification_comment(current_customer, comment.id)
    else
      render :show
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:post_id])
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!,except: [:show, :index]

 def index
  @customer = Customer.all
 end

 def show
  @customer = Customer.find(params[:id])
  @posts = @customer.posts
 end

 def edit
  @customer = Customer.find(params[:id])
 end

 def update
  @customer = Customer.find(params[:id])
  @customer.update(customer_params)
  redirect_to customer_customer_path(current_customer.id)
 end



 def withdrawal
  @customer = Customer.find(params[:customer_id])
  @customer.update(is_deleted: true)
  #is_deletedカラムにフラグを立てる（defaultはfalse)
   reset_session
   redirect_to root_path
 end


 private

 def customer_params
  params.require(:customer).permit(:nickname, :image, :body)
 end
end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController
 before_action :authenticate_customer!

def create
  @category = Category.find(params[:category_id])
  @post = Post.find(params[:post_id])
  favorite = current_customer.favorites.new(post_id: @post.id)
  favorite.save
  # 通知
  post = Post.find(params[:post_id])
  post.create_notification_favorite(current_customer)
end

def destroy
  @category = Category.find(params[:category_id])
  @post = Post.find(params[:post_id])
  favorite = current_customer.favorites.find_by(post_id: @post.id)
  favorite.destroy
end

end

app/controllers/customer/genres_controller.rb
class Customer::GenresController < ApplicationController
  def index
   @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
      @genre = Genre.new(genre_params)
    if
      @genre.save
      flash[:notice] = "追加して欲しいジャンルを送信しました"
      redirect_to customer_genres_path
    else
      flash.now[:notice] = "追加して欲しいジャンルを入力してください"
      render :new
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
    @rank = Category.group(:id).joins(:posts).order("count(posts.category_id) desc").limit(3)
    # カテゴリー別にポストを集める。
  end

  def about
  end
end

app/controllers/customer/notifications_controller.rb
class Customer::NotificationsController < ApplicationController
  before_action :authenticate_customer!

 def index
   @notifications = current_customer.passive_notifications
   @notifications.where(checked: false).each do |notification|
     notification.update_attributes(checked: true)
   end
 end

end
# 未確認の通知を受け取った後に、未確認→確認ずみになるように更新をしている

app/controllers/customer/posts_controller.rb
class Customer::PostsController < ApplicationController
   before_action :authenticate_customer!,except: [:index, :show]
  def new
    @category = Category.find(params[:category_id])
    @post = Post.new(category_id: @category.id)
  end

  def create
    @post = Post.new(post_params)
    @post.customer_id = current_customer.id
    @post.category_id = params[:category_id]

    if @post.image_or_title_present?(post_params[:images])
      @post.save
      redirect_to customer_genre_category_posts_path
    else
      flash[:notice] = "本文か画像どちらかを入力してください"
      @category = Category.find(params[:category_id])
      render :new
    end



  end

  def index
    @category = Category.find(params[:category_id])
    # eachの外に記述したいものなので定義している
    @posts = Post.where(category_id: params[:category_id])
    # 全てのpostの中から一つのカテゴリーの投稿(post)を持ってくる
    # postのcategory_idカラムのidを探す記述(category_id: params[:category_id])
  end

  def show
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to customer_genre_category_posts_path
  end

  def report
    @post = Post.find(params[:post_id])
    @post.create_notification_report(current_customer)
  end


  private
  def post_params
    params.require(:post).permit(:title, {images: []}, :tag_list)
  end


end

app/controllers/customer/relationships_controller.rb
class Customer::RelationshipsController < ApplicationController
 before_action :authenticate_customer!,except: [:followings, :followers]
 def create
   current_customer.follow(params[:customer_id])
   # 通知
   customer = Customer.find(params[:customer_id])
   customer.create_notification_follow(current_customer)
   redirect_to request.referer
 end

 def destroy
   current_customer.unfollow(params[:customer_id])
   redirect_to request.referer
 end

 def followings
   customer = Customer.find(params[:customer_id])
   @customers = customer.followings
 end

 def followers
   customer = Customer.find(params[:customer_id])
   @customer = customer.followers
 end

end

app/controllers/customer/searches_controller.rb
class Customer::SearchesController < ApplicationController

  def search
    word = params[:search][:word]
    @customers = Customer.search(word)
  end

  def tag_search
    word = params[:search][:word]
    @category = Category.find(params[:category_id])
    @posts = Post.search(word, params[:category_id])
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
      # パスワードが正しいのか確認、メソッドがfalseであるかの確認
      flash[:error] = "退会済みです"
      redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください"
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/customer/posts/_report.html.erb
<% if current_customer.present? %>
 <% if post.reported_by?(current_customer) %>
  <%= "通報ずみ"%>
 <% else %>
  <%= link_to "通報する", customer_report_path(post), class:"btn btn-outline-danger", remote: true, data: { confirm: '本当に通報しますか？' } %>
 <% end %>
<% end %>

app/views/customer/posts/_tag.html.erb
<% tag_list.each do |tag| %>
  <div class="tag"><%= tag %></div>
<% end %>

app/views/customer/posts/index.html.erb
<div class="mt-3 ml-5">
 <%= form_tag(customer_tag_search_path, method: :get) do %>
  <%= "タグ検索" %><br>
  <%= text_field_tag'search[word]'%>
  <%= hidden_field_tag 'category_id', @category.id %>
  <%= submit_tag "検索"%>
 <% end %>
</div>

<div class="container shadow-lg p-3 mb-5 bg-white rounded">
 <div class="row">
 <h1 class="col text-center mt-5 h1"><%= @category.name %></h1>
    <div class="col-lg-12 text-right">
     <% if current_customer.present? %>
      <%= link_to "", new_customer_genre_category_post_path, class: "fas fa-plus fa-5x"%>
     <% end %>
    </div>
  </div>

  <div class="row">
   <div class="col-lg-12">
    <table>
     <tbody>
        <% @posts.each do |post| %>
          <tr><td><%= post.created_at.strftime('%Y/%m/%d')%></td></tr>
          <tr><td><%= link_to post.customer.nickname, customer_customer_path(post.customer_id) %></td></tr>
          <tr>
           <td class="article">
           <% post.images.each do |image| %>
            <%= image_tag image, size: "300x250" %>
           <% end %>
           </td>
          <td class="pl-2"><%= post.title %></td>
          </tr>
        <tr>
         <td id="favorite_buttons_<%= post.id %>">
           <%= render "customer/favorites/favorites", post: post, category: @category %>
         </td>
         <td nowrap><%= link_to "#{post.comment.count}コメント", customer_genre_category_post_path(@category.genre_id,@category,post),class: "far fa-comment-dots"%></td>
         <td nowrap><%= render 'customer/posts/tag', tag_list: post.tag_list %></td>
        </tr>
        <tr class="border-bottom border-info"><td class="text-right" id="report_<%= post.id %>">
         <%= render 'customer/posts/report', post: post %>
        </td></tr>
       <% end %>
     </tbody>
    </table>
   </div>
 </div>

</div>

app/views/customer/posts/new.html.erb
<div class="text-danger">
<%= flash[:notice] %>
</div>
<%= form_with model: @post, url: customer_genre_category_posts_path(@category.genre_id,@post.category_id), local:true do |f| %>
<!--ネストしているためidが二つ必要-->
 <div class="ml-5 mt-5"><h2 class="border-bottom"><%= @category.name+"に関することを投稿しましょう！！！"%></h2></div>
 <div class="row">
  <div class="col ml-5"><%= f.text_area :title , size:"70x8" %></div>
  <div class="col"><h4><%= f.label "画像"%></h4><br>
   <%= f.file_field :images, multiple: true%>
  </div>
 </div>
 <div class="ml-5">
  <%= f.label :タグをつけることができます！ %>,で区切ることで複数のタグをつけることができます！<br>
  <%= f.text_field :tag_list, value: @post.tag_list.join(',')%>
 </div>
 <div class="col-lg-10 text-right"><%= f.submit '投稿', class: "btn btn-info btn-lg"%></div>
<% end %>
<h6 class="border rounded border-danger col-lg-4 ml-5">※投稿はコメント欄から削除することができます<br>1度投稿したものを編集することはできません</h6>

app/views/customer/posts/report.js.erb
$("#report_<%= @post.id %>").html("<%= j(render 'customer/posts/report', post: @post) %>");

app/views/customer/posts/show.html.erb
<div class="container">
  <div class="row">
    <table class="col-lg-12 mt-5">
      <tbody>
        <tr><td><%= @post.created_at.strftime('%Y/%m/%d')%></td>
        <tr><td><%= @post.customer.nickname %></td></tr>
        <tr>
         <td>
          <% @post.images.each do |image| %>
           <%= image_tag image, size: "300x250" %>
          <% end %>
         </td>
         <td><%= @post.title %></td>
        </tr>
        <tr>
          <td></td>
          <td id="favorite_buttons_<%= @post.id %>">
           <%= render "customer/favorites/favorites", post: @post, category: @category %>
          </td>
          <td nowrap id="comment_count_<%= @post.id %>"><%= render "customer/comments/count", post: @post %></td>
          <% if @post.written_by?(current_customer) %>
           <td nowrap><%= link_to "投稿を削除",customer_genre_category_post_path(@category.genre_id,@category,@post), method: :delete, class: "btn btn-danger"%></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="row">
    <div class="col-lg-12">
     <% if current_customer.present?%>
       <%= form_with(model: @comment, url: customer_genre_category_post_comments_path(@category.genre_id,@category,@post,@comment),remote: true) do |f| %>
        <%= f.text_area :comment,placeholder: "コメントをここに", size: "50x4"%>
        <%= f.submit "コメントする！"%>
       <% end %>
      <% end %>
    </div>
  </div>

   <div class="shadow-lg p-3 mb-5 bg-white rounded">
   <h3>コメント欄</h3>
      <div id="post_comments_<%= @post.id %>">
           <%= render "customer/comments/comments", post: @post, category: @category %>
      </div>
   </div>
  </div>
</div>